import { describe, expect, it } from 'vitest';
import { svgToIconUri } from './icon.helper';
import { BaseIcons } from './icon.records';

const svg = (inner: string, attrs = "viewBox='0 0 24 24'") =>
  `<svg xmlns="http://www.w3.org/2000/svg" ${attrs.replace(/'/g, '"')}>${inner}</svg>`;

const decode = (uri: string) => decodeURIComponent(uri.replace(/^data:image\/svg\+xml[^,]*,/, ''));

describe('svgToIconUri', () => {
  it('encodes a plain icon to a mask-ready data URI', () => {
    const uri = svgToIconUri(svg('<path d="M4 4h16v16H4z"/>'));
    expect(uri).toMatch(/^data:image\/svg\+xml,/);
    expect(decode(uri)).toBe(
      "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M4 4h16v16H4z'/></svg>"
    );
  });

  it('escapes the characters a data URI cannot carry raw', () => {
    const uri = svgToIconUri(svg('<path fill="#123456" d="M0 0h1v1H0z"/>'));
    expect(uri).toContain('%3csvg');
    expect(uri).toContain('%23123456');
    expect(uri).not.toContain('<');
    expect(uri).not.toContain('>');
    // Single quotes throughout, so the result drops into a "…" TS string.
    expect(uri).not.toContain('"');
  });

  it('strips fixed width/height so the mask scales to its container', () => {
    const uri = svgToIconUri(
      '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><path d="M0 0h48v48H0z"/></svg>'
    );
    const out = decode(uri);
    expect(out).not.toMatch(/width=/);
    expect(out).not.toMatch(/height=/);
    expect(out).toContain("viewBox='0 0 48 48'");
  });

  it('drops xml declarations, doctypes and comments', () => {
    const uri = svgToIconUri(
      `<?xml version="1.0"?><!DOCTYPE svg><!-- Generated by Illustrator -->${svg('<path d="M0 0h1v1H0z"/>')}`
    );
    const out = decode(uri);
    expect(out).not.toContain('<?xml');
    expect(out).not.toContain('DOCTYPE');
    expect(out).not.toContain('<!--');
    expect(out.startsWith('<svg')).toBe(true);
  });

  it('is idempotent — re-encoding its own output is a no-op', () => {
    const once = svgToIconUri(svg('<path d="M4 4h16v16H4z"/>'));
    expect(svgToIconUri(decode(once))).toBe(once);
  });

  describe('accepts artwork that survives masking', () => {
    it('a single fill color', () => {
      expect(() => svgToIconUri(svg('<path fill="#E8112D" d="M0 0h1v1H0z"/>'))).not.toThrow();
    });

    it('fill="none" with a stroke — "none" paints nothing, so it is not a color', () => {
      expect(() =>
        svgToIconUri(svg('<circle cx="12" cy="12" r="8" fill="none" stroke="#000"/>'))
      ).not.toThrow();
    });

    it('a transparent spacer rect alongside the artwork', () => {
      expect(() =>
        svgToIconUri(
          svg('<path fill="none" d="M0 0h24v24H0z"/><path fill="#000" d="M4 4h4v4H4z"/>')
        )
      ).not.toThrow();
    });

    it('the same color repeated across shapes', () => {
      expect(() =>
        svgToIconUri(svg('<path fill="#000" d="M0 0h4v4H0z"/><path fill="#000" d="M8 8h4v4H8z"/>'))
      ).not.toThrow();
    });
  });

  describe('rejects artwork that would silently break', () => {
    it('a multi-color brand mark, naming the colors', () => {
      expect(() =>
        svgToIconUri(svg('<path fill="#E8112D" d="M0 0h1v1H0z"/><circle fill="#0052FF" r="4"/>'), {
          name: 'acmeLogo',
        })
      ).toThrow(/acmeLogo: paints in 2 colors \(#e8112d, #0052ff\).*silhouette/s);
    });

    it('multi-color declared via style attributes', () => {
      expect(() =>
        svgToIconUri(
          svg('<path style="fill:#fff" d="M0 0h1v1H0z"/><path style="fill:#000" d="M2 2h1v1H2z"/>')
        )
      ).toThrow(/paints in 2 colors/);
    });

    it('a gradient fill', () => {
      expect(() => svgToIconUri(svg('<path fill="url(#grad)" d="M0 0h1v1H0z"/>'))).toThrow(
        /gradient or pattern/
      );
    });

    it('a missing viewBox', () => {
      expect(() =>
        svgToIconUri(
          '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M0 0h1v1H0z"/></svg>'
        )
      ).toThrow(/no viewBox/);
    });

    it('an embedded raster image', () => {
      expect(() => svgToIconUri(svg('<image href="logo.png" width="24" height="24"/>'))).toThrow(
        /raster <image>/
      );
    });

    it('an external reference', () => {
      expect(() =>
        svgToIconUri(svg('<use href="https://cdn.example.com/sprite.svg#icon"/>'))
      ).toThrow(/external resource/);
      // …but an internal fragment reference is fine.
      expect(() =>
        svgToIconUri(svg('<use href="#local"/><path id="local" d="M0 0h1v1H0z"/>'))
      ).not.toThrow();
    });

    it('markup that is not an SVG document', () => {
      expect(() => svgToIconUri('<div>nope</div>')).toThrow(/not a complete <svg> document/);
      expect(() => svgToIconUri('')).toThrow(/empty SVG source/);
    });
  });

  it('allows a multi-color source when the silhouette is intended', () => {
    const two = svg('<path fill="#E8112D" d="M0 0h1v1H0z"/><circle fill="#0052FF" r="4"/>');
    expect(() => svgToIconUri(two, { allowMultiColor: true })).not.toThrow();
  });

  it('reproduces the committed BaseIcons byte-for-byte', () => {
    // The generator and this helper must agree, or icons added by a brand team
    // would be encoded differently from the built-in set.
    for (const [name, uri] of Object.entries(BaseIcons)) {
      if (name === 'spinner') continue; // hand-authored: carries CSS, not plain artwork
      expect(svgToIconUri(decode(uri), { name })).toBe(uri);
    }
  });
});
