import { CSSProperties } from 'react';
import { HorizontalAlign, VerticalAlign } from '@uni/core';
export declare const flex: CSSProperties;
export declare const row: CSSProperties;
export declare const column: CSSProperties;
export declare const alignTop: CSSProperties;
export declare const alignCenter: CSSProperties;
export declare const alignBottom: CSSProperties;
export declare const FlexVerticalAlignments: Record<VerticalAlign, CSSProperties>;
export declare const justifyLeft: CSSProperties;
export declare const justifyCenter: CSSProperties;
export declare const justifyRight: CSSProperties;
export declare const FlexHorizontalAlignments: Record<HorizontalAlign, CSSProperties>;
export declare const expand: CSSProperties;
export declare const fix: CSSProperties;
export declare const rowFlexItem: CSSProperties;
export declare const rowFixedItem: CSSProperties;
export declare const flexRowStart: CSSProperties;
export declare const flexRowCenter: CSSProperties;
export declare const flexRowEnd: CSSProperties;
export declare const spaceBetween: CSSProperties;
export declare const flexRowSpaceBetween: CSSProperties;
export declare const flexRowSpaceAround: CSSProperties;
export declare const spaceEvenly: CSSProperties;
export declare const flexRowSpaceEvenly: CSSProperties;
export declare const flexColumnCenter: CSSProperties;
export declare const flexColumnSpaceAround: CSSProperties;
export declare const flexOff: CSSProperties;
//# sourceMappingURL=flex.style.d.ts.map